### PR TITLE
gemini: Merge MIUI 7.3.2 global dev configs

### PR DESCRIPTION
**Pull request by raiko86**
Fixes Xiaomi Mi In-Ear Headphones Pro sound when calling

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks, but there's already an open change on Gerrit for this (https://review.lineageos.org/#/c/161712/). In the future, please use Gerrit for any contributions. Could you close this pull request and detail there (in Gerrit's change) more about the issue you were experiencing?

**Comment by bgcngm** [comment]
@raiko86 please close this pull request. Change mentioned above has been merged.

**Comment by bgcngm** [comment]
@raiko86, could you explain more about the issue you tried to fix? The addition of **COMP1 Switch** and **COMP2 Switch** lines messes up offline audio playing with Google Play Music. Every system sound makes the volume decrease instantly and then it returns to normal. When I tried the new configs I only tested Spotify and it doesn't happen there.

**Comment by bgcngm** [comment]
This is going to be reverted: https://review.lineageos.org/#/c/165814/.

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at https://zifnab.net/~zifnab/wiki_dump/Howto:_Gerrit.html

Thanks!

**Pull request closed without merging**
